#!/bin/sh

~/.config/bspwm/settings

trayer  --edge bottom --align left --height 16 --transparent true --alpha 255 --expand true &
#stalonetray &

xrdb ~/.Xresources
#nitrogen --restore
xsetroot -solid "#171717"
zeal &

export PANEL_FIFO=/home/anthony/.panel-fifo
export PANEL_HEIGHT=20
export PANEL_FONT_FAMILY="-*-Terminus-medium-r-*-*-*-*-*-*-*-*-*-*"

~/.config/bspwm/panel &
