#!/bin/sh

~/.config/bspwm/settings

trayer  --edge bottom --align left --height 16 --transparent true --alpha 256 --expand true &

xrdb ~/.Xresources
nitrogen --restore

export PANEL_FIFO=/home/anthony/.panel-fifo
export PANEL_HEIGHT=20
export PANEL_FONT_FAMILY="-*-Terminus-medium-r-*-*-*-*-*-*-*-*-*-*"

~/.config/bspwm/panel &
