#!/bin/sh

~/.config/bspwm/settings

xbacklight -set 40 &

trayer  --edge bottom --align left --height 24 --transparent true --alpha 255 --expand true &

sxhkd &

nm-applet &
cbatticon -n &
volumeicon &

#light-locker &

#compton -bcfG -l -11 -t -11 -r 8 -D 2 -I 0.06 -O 0.06

xrdb ~/.Xresources

nitrogen --restore &

export PANEL_FIFO=/home/anthony/.panel-fifo

~/.config/bspwm/panel &
