#! /bin/sh

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT


[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc config top_padding $PANEL_HEIGHT
bspc control --subscribe > "$PANEL_FIFO" &

while true; do
	date +"T%H:%M" > "$PANEL_FIFO"
	date +"D%b %d" > "$PANEL_FIFO"
	~/.config/bspwm/battery.py > "$PANEL_FIFO"
	~/.config/bspwm/volume.py > "$PANEL_FIFO"
	~/.config/bspwm/internet.py > "$PANEL_FIFO"
	echo A`xtitle` > "$PANEL_FIFO"
	sleep 0.5s
done &

PANEL_HEIGHT=24

PANEL_FONT_1="-*-Terminus-medium-r-*-*-*-*-*-*-*-*-*-*"
PANEL_FONT_2="-wuncon-siji-medium-r-normal--10-100-75-75-c-80-iso10646-1"

cat "$PANEL_FIFO" | ~/.config/bspwm/bar_parse.py | lemonbar -g 1920x$PANEL_HEIGHT -f "$PANEL_FONT_1" -f "$PANEL_FONT_2" -F "#FF777777" -B "#FF222222" | sh &

wait
