#! /bin/sh

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT


[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc config top_padding $PANEL_HEIGHT
bspc control --subscribe > "$PANEL_FIFO" &

while true; do
	date +"T%H:%M" > "$PANEL_FIFO"
	date +"D%b %d" > "$PANEL_FIFO"
	~/.config/bspwm/battery.py > "$PANEL_FIFO"
	~/.config/bspwm/volume.py > "$PANEL_FIFO"
	~/.config/bspwm/internet.py > "$PANEL_FIFO"
	echo A`xtitle` > "$PANEL_FIFO"
	sleep 0.5s
done &

PANEL_FONT_3="desktops:size=12"
PANEL_FONT_2="iconfont:size=12"
PANEL_FONT_1="Droid Sans:size=10"

PANEL_HEIGHT=30

cat "$PANEL_FIFO" | ~/.config/bspwm/bar_parse.py | ~/dev/bar2/lemonbar -g 1920x$PANEL_HEIGHT -f "$PANEL_FONT_1" -f "$PANEL_FONT_2" -f "$PANEL_FONT_3" -F "#FFFFFFFF" -B "#FF222222" -u 2 | sh &

wait
