#!/bin/sh

bspc config border_width       4
bspc config window_gap         12

bspc config top_padding 30
bspc config bottom_padding 0

bspc config initial_polarity second_child

bspc config click_to_focus true
bspc config pointer_follows_focus true

bspc config pointer_modifier control
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config split_ratio         0.50
bspc config gapless_monocle     true

bspc monitor -d "α" "β" "γ" "δ" "ε" "ζ" "η"
#bspc monitor -d web dev comm game misc

#bspc monitor -d " 1 " " 2 " " 3 " " 4 " " 5 " " 6 " " 7 "

#bspc monitor -d " $(echo -e '\uf800') " " $(echo -e '\uf801') " " $(echo -e '\uf802') " " $(echo -e '\uf803') " " $(echo -e '\uf804') " " $(echo -e '\uf804\u001a') "

bspc config normal_border_color "#1F1F1F"
bspc config focused_border_color "#008055"
bspc config presel_feedback_color "#ff0000"

bspc rule -a Firefox desktop=^1 focus=on
bspc rule -a Sublime_text desktop=^2 
bspc rule -a ts3client_linux_amd64 desktop=^3
bspc rule -a Quake3-UrT.x86_64 desktop=^4 floating=on
bspc rule -a Steam desktop=^4 floating=on
bspc rule -a Zeal floating=on
bspc rule -a zeal floating=on
bspc rule -a urtsb floating=on
bspc rule -a urxvt_float floating=on
