[theme]
name = "plain"
[theme.overrides]
idle_bg = "#08111b"
idle_fg = "#A4B9CC"
info_bg = "#17324F"
info_fg = "#E6F3FF"
good_bg = "#365C5B"
good_fg = "#E6F3FF"
warning_bg = "#B3AE7D"
warning_fg = "#E6F3FF"
critical_bg = "#AD5768"
critical_fg = "#E6F3FF"
separator = ""
# separator_bg = auto
# separator_fg = auto
alternating_tint_bg = "#000000"
alternating_tint_fg = "#000000"

[icons]
name = "awesome"
[icons.overrides]
# music = "    "
music = "    "
time = " "
memory_mem = "   "
memory_swap = " [] "
cpu = "   "
bat = "   "
bat_full = "   "
bat_charging = "   "
bat_discharging = "   "
volume_muted = " "

[[block]]
block = "music"
max_width = 32
player = "spotify"
buttons = ["play", "next"]

[[block]]
block = "memory"
clickable = true
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"
warning_mem = 70
critical_mem = 90

[[block]]
block = "cpu"
interval = 1
info = 50
warning = 70
critical = 90

[[block]]
block = "sound"
interval = 1

[[block]]
block = "battery"
device = 0

[[block]]
block = "battery"
device = 1

[[block]]
block = "time"
interval = 30
format = " %b %d, %l:%M %P "
